name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Tarpaulin
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-tarpaulin
        version: 0.14.2
        use-tool-cache: true

    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --verbose

    - name: Lint
      run: cargo fmt --check --verbose

    - name: Test
      run: cargo test --verbose